### PR TITLE
First draft of Hello World Tutorial

### PR DESCRIPTION
**Pull request by luttje**
[Direct link to the tutorials](https://github.com/luttje/GmodDotNet/tree/doc-tutorials/docfx_project/articles/tutorials)

I got carried away tonight writing a comprehensive Hello World Tutorial. It's a bit much (4000+ words), so perhaps we'll choose to strip it down to a more concise tutorial.

The target audience I wrote it for has written no other code besides Lua in Garry's Mod.

This is a first draft so I advise to label it do-not-merge. It also contains the full solution right there in the docs for now. In time the solution should be placed on the examples GitHub.

(I didn't test the docfx additions I made, I haven't set up a testing environment for that yet)

C & C is much appreciated. I can probably only continue next Monday, though I may see some more time in the evenings this week.

### CODE REVIEW

**Comment by luttje** [comment]
#68

I'm thinking I'll turn this single tutorial into multiple tutorials: 
1. A quick start with Hello World
2. A comprehensive introduction to Visual Studio, C# and the Hello World code

For the quick start I'll strip all explaining and just stick to the straight forward instructions and images. The quick start would be helpful to anyone with already some experience in C#

For the comprehensive guide I'm thinking to split up the single .md file into multiple linked pages with a toc as index. This should make it easier to follow.

**Comment by SupinePandora43** [comment]
you say `.NET Core 3.1 Runtime (LTS)`, why not `.NET 5` or `.NET 6`?

**Comment by luttje** [comment]
> 
> 
> you say `.NET Core 3.1 Runtime (LTS)`, why not `.NET 5` or `.NET 6`?

Heya good question, I was building the tutorial based on the latest release (0.6.0). I'm aware it's far behind. It's version is at least 3.1 according to the nuget dependencies. Though I was planning on explaining how to use the nightly NuGet package in a seperate tutorial

**edit:** Alternatively we could update the release to use the latest .NET 5 nightly version

**Comment by GlebChili** [comment]
> **edit:** Alternatively we could update the release to use the latest .NET 5 nightly version

@luttje Docs are considered to be part of 0.7.0 release, so we can forget about .NET Core 3.1 😄

**Comment by SupinePandora43** [comment]
What will be released first? 0.7.0 or net6?

**Comment by GlebChili** [comment]
@SupinePandora43 0.7.0, hopefully.

**Comment by luttje** [comment]
I believe I've removed all references to 3.1 and the old loading system.

This PR should be completely about .NET 5.0 and the upcoming release 0.7.0 now

**Review by GlebChili — APPROVED** [review]
Amazing work! LGTM.

**Pull request merged**
