### PR TITLE
Feature load module from any location

### LINKED ISSUE #105: [ENH] Allow modules to be loaded from any folder
# Description

We should add an option to load GmodDotNet modules from any folder on disk, not only `lua/bin/Modules`. This can enhance development inner loop performance since users can load modules directly from MSBuild project's output folder (like `bin/Debug/net5.0`) without need to copy build artifacts for each update. 

# Implementation details

We should check if an argument of `dotnet.load` function is a full path to a .NET assembly and try to load it in this case.

# Security considerations

Since `dotnet.load` is a part of GmodDotNet Lua API, server owners can potentially make clients load modules, which were not properly installed. This is problematic. Thus loading modules from arbitrary location should be an opt-in feature. I suggest to use environment variable, something like `GMODNET_ALLOW_ANY_FOLDER`, as a turn on switch.

### PR DESCRIPTION
**Pull request by GlebChili**
Closes #105

### CODE REVIEW

**Comment by luttje** [comment]
Good idea! 

One request: Could you include an example in the docs on how to include a module from some locations on the device?

Like a project stored in the default VS2019's solution path: `%UserProfile%\source\repos\`
or in `C:\Projects\`

At the moment it's not really clear to me how that's done

**Review by SupinePandora43 — APPROVED** [review]
Lgtm

**Comment by GlebChili** [comment]
@luttje I have added example to `dotnet.load` docs: https://ambitious-hill-0f19b7c03-107.westeurope.azurestaticapps.net/lua-api/dotnet.html#loadstring. Take a look.

**Comment by luttje** [comment]
> 
> 
> @luttje I have added example to `dotnet.load` docs: https://ambitious-hill-0f19b7c03-107.westeurope.azurestaticapps.net/lua-api/dotnet.html#loadstring. Take a look.

Awesome, if you could copy the example to the article `docfx_project/articles/runtime_features/development_environment/index.md` that would make the article a bit more instructive.

Looks good otherwise. Thanks!

**Comment by GlebChili** [comment]
@luttje Done! Take a look: https://ambitious-hill-0f19b7c03-107.westeurope.azurestaticapps.net/articles/runtime_features/development_environment/index.html

**Pull request merged**
