### PR TITLE
Upgrade to .NET 6

### LINKED ISSUE #89: [ENH] Update bundled .NET runtime to version 6.0

### PR DESCRIPTION
**Pull request by GlebChili**

### CODE REVIEW

**Comment by SupinePandora43** [comment]
why force-push?

**Comment by GlebChili** [comment]
@SupinePandora43 Cause I always rebase this branch to `main`.

**Comment by GlebChili** [comment]
Automatic rebase to main has failed. Manual rebase is required.

**Comment by GlebChili** [comment]
Automatic rebase to 'main' has failed. Manual rebase is required.

**Comment by GlebChili** [comment]
Automatic rebase to branch 'main' has failed. Manual rebase is required.

**Pull request merged**
